services:
  # ------------------------
  # MySQL
  # ------------------------
  mysql:
    image: mysql:8.0
    container_name: grupo1_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - grupo1_mysql_data:/var/lib/mysql
    networks:
      - internal

  # ------------------------
  # PHP-FPM
  # ------------------------
  php:
    build:
      context: .
      dockerfile: ./docker/dockerfiles/php.dockerfile
    container_name: grupo1_php
    volumes:
      - ./backend:/var/www/html/backend
    depends_on:
      - mysql
    command: >
      sh -c "chown -R www-data:www-data /var/www/html/backend/storage /var/www/html/backend/bootstrap/cache
      && chmod -R 775 /var/www/html/backend/storage /var/www/html/backend/bootstrap/cache
      && php-fpm"
    networks:
      - internal

  # ------------------------
  # Nginx (Frontend + Backend)
  # ------------------------
  nginx:
    image: nginx:alpine
    container_name: grupo1_nginx
    volumes:
      - ./backend:/var/www/html/backend
      - ./frontend/dist:/var/www/html/frontend
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - proxy_network
      - internal

  # ------------------------
  # PhpMyAdmin
  # ------------------------
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: grupo1_phpmyadmin
    restart: always
    ports:
      - "9010:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
    depends_on:
      - mysql
    networks:
      - internal

  # ------------------------
  # n8n
  # ------------------------
  n8n:
    image: n8nio/n8n
    container_name: grupo1_n8n
    restart: always
    ports:
      - "5010:5678"
    environment:
      - GENERIC_TIMEZONE=America/Bogota
    volumes:
      - grupo1_n8n_data:/home/node/.n8n
    networks:
      - internal

# ------------------------
# Volumes
# ------------------------
volumes:
  grupo1_mysql_data:
  grupo1_n8n_data:

# ------------------------
# Networks
# ------------------------
networks:
  proxy_network:
    external: true
  internal:
    driver: bridge