services:
  # ------------------------
  # MySQL
  # ------------------------
  mysql:
    image: mysql:8.0
    platform: linux/arm64/v8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"

  # ------------------------
  # PHP-FPM
  # ------------------------
  php:
    build:
      context: .
      dockerfile: ./docker/dockerfiles/php.dockerfile
    container_name: php_fpm
    volumes:
       - ./backend:/var/www/html
    depends_on:
      - mysql

  # ------------------------
  # Nginx
  # ------------------------
  nginx:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  # ------------------------
  # PhpMyAdmin
  # ------------------------
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    platform: linux/amd64   # 👈 Forzar compatibilidad en Mac M1/M2
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
    depends_on:
      - mysql

  # ------------------------
  # n8n
  # ------------------------
  n8n:
    image: n8nio/n8n
    platform: linux/arm64/v8
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=America/Bogota
    volumes:
      - ./docker/n8n:/home/node/.n8n
