


server {
    listen 80;
    server_name localhost;

    
    # Raíz: Frontend React
    root /var/www/html/frontend;
    index index.html;
    client_max_body_size 20M;

    # Logs
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    # Frontend - SPA React
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Backend API Laravel
    location /api {
        alias /var/www/html/backend/public;
        try_files $uri $uri/ @laravel;

        location ~ \.php$ {
            fastcgi_pass php:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME /var/www/html/backend/public/index.php;
            include fastcgi_params;
        }
    }

    location @laravel {
        rewrite /api/(.*)$ /api/index.php?/$1 last;
    }

    # Servir archivos de storage de Laravel
    location /storage {
        alias /var/www/html/public/storage;
        expires 1y;
        add_header Cache-Control "public, immutable";
        access_log off;
        try_files $uri =404;
    }

    # Archivos estáticos con caché
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # Denegar acceso a archivos ocultos
    location ~ /\. {
        deny all;
    }
}