-- MySQL Script generated by MySQL Workbench
-- Thu Sep 25 16:47:10 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`roles` (
  `role_id` INT NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(100) NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `user_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  `password_hash` VARCHAR(500) NULL,
  `phone_number` VARCHAR(100) NULL,
  `adress_details` VARCHAR(300) NULL,
  `is_verified` TINYINT(3) NULL,
  `created_at` DATE NULL,
  `roles_role_id` INT NOT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_users_roles1_idx` (`roles_role_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_roles1`
    FOREIGN KEY (`roles_role_id`)
    REFERENCES `mydb`.`roles` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`products` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `description` VARCHAR(400) NULL,
  `image_url` VARCHAR(300) NULL,
  `created_at` DATE NULL,
  PRIMARY KEY (`product_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`departments` (
  `department_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NULL,
  PRIMARY KEY (`department_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`municipalities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`municipalities` (
  `municipality_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NULL,
  `departments_department_id` INT NOT NULL,
  PRIMARY KEY (`municipality_id`),
  INDEX `fk_municipalities_departments_idx` (`departments_department_id` ASC) VISIBLE,
  CONSTRAINT `fk_municipalities_departments`
    FOREIGN KEY (`departments_department_id`)
    REFERENCES `mydb`.`departments` (`department_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`price_references`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`price_references` (
  `price_ref_id` INT NOT NULL AUTO_INCREMENT,
  `price_per_kg` DECIMAL(10,2) NULL,
  `date` DATE NULL,
  `source` VARCHAR(200) NULL,
  `products_product_id` INT NOT NULL,
  `municipalities_municipality_id` INT NOT NULL,
  PRIMARY KEY (`price_ref_id`),
  INDEX `fk_price_references_products1_idx` (`products_product_id` ASC) VISIBLE,
  INDEX `fk_price_references_municipalities1_idx` (`municipalities_municipality_id` ASC) VISIBLE,
  CONSTRAINT `fk_price_references_products1`
    FOREIGN KEY (`products_product_id`)
    REFERENCES `mydb`.`products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_price_references_municipalities1`
    FOREIGN KEY (`municipalities_municipality_id`)
    REFERENCES `mydb`.`municipalities` (`municipality_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`price_alerts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`price_alerts` (
  `alert_id` INT NOT NULL AUTO_INCREMENT,
  `condition` ENUM('ABOVE', 'BELOW') NULL,
  `threshold_price` DECIMAL(10,2) NULL,
  `created_at` DATE NULL,
  `users_user_id` BIGINT(20) NOT NULL,
  `products_product_id` INT NOT NULL,
  `status` ENUM('ACTIVE', 'INACTIVE', 'DELETED') NULL,
  `municipalities_municipality_id` INT NOT NULL,
  PRIMARY KEY (`alert_id`),
  INDEX `fk_price_alerts_users1_idx` (`users_user_id` ASC) VISIBLE,
  INDEX `fk_price_alerts_products1_idx` (`products_product_id` ASC) VISIBLE,
  INDEX `fk_price_alerts_municipalities1_idx` (`municipalities_municipality_id` ASC) VISIBLE,
  CONSTRAINT `fk_price_alerts_users1`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_price_alerts_products1`
    FOREIGN KEY (`products_product_id`)
    REFERENCES `mydb`.`products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_price_alerts_municipalities1`
    FOREIGN KEY (`municipalities_municipality_id`)
    REFERENCES `mydb`.`municipalities` (`municipality_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`post_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`post_types` (
  `type_id` INT NOT NULL AUTO_INCREMENT,
  `type_name` VARCHAR(45) NULL,
  `type_desc` VARCHAR(400) NULL,
  PRIMARY KEY (`type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`posts` (
  `post_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NULL,
  `description` VARCHAR(400) NULL,
  `quantity_kg` DECIMAL(10,2) NULL,
  `price_per_kg` DECIMAL(10,2) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `post_types_type_id` INT NOT NULL,
  `products_product_id` INT NOT NULL,
  `users_user_id` BIGINT(20) NOT NULL,
  `municipalities_municipality_id` INT NOT NULL,
  `status` ENUM('ACTIVE', 'CLOSED', 'EXPIRED') NULL,
  PRIMARY KEY (`post_id`),
  INDEX `fk_posts_post_types1_idx` (`post_types_type_id` ASC) VISIBLE,
  INDEX `fk_posts_products1_idx` (`products_product_id` ASC) VISIBLE,
  INDEX `fk_posts_users1_idx` (`users_user_id` ASC) VISIBLE,
  INDEX `fk_posts_municipalities1_idx` (`municipalities_municipality_id` ASC) VISIBLE,
  CONSTRAINT `fk_posts_post_types1`
    FOREIGN KEY (`post_types_type_id`)
    REFERENCES `mydb`.`post_types` (`type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posts_products1`
    FOREIGN KEY (`products_product_id`)
    REFERENCES `mydb`.`products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posts_users1`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posts_municipalities1`
    FOREIGN KEY (`municipalities_municipality_id`)
    REFERENCES `mydb`.`municipalities` (`municipality_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`post_images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`post_images` (
  `image_id` INT NOT NULL AUTO_INCREMENT,
  `image_url` VARCHAR(300) NULL,
  `uploaded_at` DATETIME NULL,
  `posts_post_id` INT NOT NULL,
  PRIMARY KEY (`image_id`),
  INDEX `fk_post_images_posts1_idx` (`posts_post_id` ASC) VISIBLE,
  CONSTRAINT `fk_post_images_posts1`
    FOREIGN KEY (`posts_post_id`)
    REFERENCES `mydb`.`posts` (`post_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reviews` (
  `review_id` INT NOT NULL AUTO_INCREMENT,
  `rating` INT NULL,
  `comment` VARCHAR(400) NULL,
  `created_at` DATETIME NULL,
  `reviewer_id` BIGINT(20) NOT NULL,
  `reviewed_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`review_id`),
  INDEX `fk_reviews_users1_idx` (`reviewer_id` ASC) VISIBLE,
  INDEX `fk_reviews_users2_idx` (`reviewed_id` ASC) VISIBLE,
  CONSTRAINT `fk_reviews_users1`
    FOREIGN KEY (`reviewer_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reviews_users2`
    FOREIGN KEY (`reviewed_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_publication_favorites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_publication_favorites` (
  `users_user_id` BIGINT(20) NOT NULL,
  `posts_post_id` INT NOT NULL,
  `date` DATETIME NULL,
  PRIMARY KEY (`users_user_id`, `posts_post_id`),
  INDEX `fk_users_has_posts_posts1_idx` (`posts_post_id` ASC) VISIBLE,
  INDEX `fk_users_has_posts_users1_idx` (`users_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_posts_users1`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_posts_posts1`
    FOREIGN KEY (`posts_post_id`)
    REFERENCES `mydb`.`posts` (`post_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
